services:
  postgres-eng-software:
    image: 'postgres:16-alpine'
    container_name: 'postgres-eng-software'
    environment:
      - 'POSTGRES_DB=eng_software_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
    networks:
      - eng-network

  eng-software-game:
    image: eng-software-game
    restart: always
    build: .
    working_dir: /eng-software-game
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/eng_software_db
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - postgres-eng-software
    networks:
      - eng-network

networks:
  eng-network:
    driver: bridge